### PR TITLE
Avni - intake subsystem issue fixed

### LINKED ISSUE #8: Intake Subsystem
2 Motors (on CANSparkMax), one should be inverted from the other.
Motors should follow each other
Trigger power when button is pressed (button # TBD)

### PR DESCRIPTION
**Pull request by ItsAvs**
I explained more in issues, but mostly had trouble with class variable for PIDcontroller

### CODE REVIEW

File: src/main/java/frc/robot/Constants.java [hunk 1]
```diff
@@ -30,6 +30,13 @@ public static class ControllerConstants {
      * 12 (COD)
      */
     public static class PortConstants {
+        public static final int LEADER_INTAKE_MOTOR_ID              = 42; //THE MEANING OF LIFE -- change later
+        public static final int FOLLOWER_INTAKE_MOTOR_ID            = 13; //bad scawy number -- change later
+        public static final int LEADER_INTAKE_ENCODER_ID            = 15; // change
```
Comment (ebay-kid) [inline src/main/java/frc/robot/Constants.java]: The `ENCODER_ID` here and the one right below it can be removed

File: src/main/java/frc/robot/Constants.java [hunk 2]
```diff
@@ -44,6 +51,10 @@ public static class PortConstants {
         public static final int FRONT_RIGHT_ROTATION_CANCODER_ID    = 3;
         public static final int BACK_LEFT_ROTATION_CANCODER_ID      = 6;
         public static final int BACK_RIGHT_ROTATION_CANCODER_ID     = 1;
+
+
+        //WMP
```
Comment (ebay-kid) [inline src/main/java/frc/robot/Constants.java]: PWM

File: src/main/java/frc/robot/subsystems/intake/IntakeSubsytem.java [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+    public double getPivotPosition(){
+        return pivotEncoder.getPosition();
+    }
+
+    public void setPivotSpeed(double pivotSpeed){
+        pivotMotor.set(pivotSpeed);
+    }
+
+    public void setPivotEncodePosition(double position){
```
Comment (ebay-kid) [inline src/main/java/frc/robot/subsystems/intake/IntakeSubsytem.java]: `EncoderPosition`

File: src/main/java/frc/robot/subsystems/intake/IntakeSubsytem.java [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+
+    private final DigitalInput intakeLimitSwitch;
+
+    private final SparkPIDController pivotPIDController;
+
+
+    public IntakeSubsytem(){
+        leaderMotor = new CANSparkMax(PortConstants.LEADER_INTAKE_MOTOR_ID, MotorType.kBrushless);
+        followerMotor = new CANSparkMax(PortConstants.FOLLOWER_INTAKE_MOTOR_ID, MotorType.kBrushless);
+        followerMotor.setInverted(true);
```
Comment (ebay-kid) [inline src/main/java/frc/robot/subsystems/intake/IntakeSubsytem.java]: The `setInverted` might not be necessary - maybe comment it out but leave it there in case we do need it

File: src/main/java/frc/robot/Constants.java [hunk 5]
```diff
@@ -30,6 +30,13 @@ public static class ControllerConstants {
      * 12 (COD)
      */
     public static class PortConstants {
+        public static final int LEADER_INTAKE_MOTOR_ID              = 42; //THE MEANING OF LIFE -- change later
```
Comment (ebay-kid) [inline src/main/java/frc/robot/Constants.java]: I'd actually name this one (and the follower) as specifically `TOP_INTAKE` and `BOTTOM_INTAKE` - the labels in the Subsystem are purely for our own reference in terms of which one is leading and which isn't. Naming this constant as the actual top/bottom makes it more clear + more flexible.

File: src/main/java/frc/robot/Constants.java [hunk 6]
```diff
@@ -44,6 +51,10 @@ public static class PortConstants {
         public static final int FRONT_RIGHT_ROTATION_CANCODER_ID    = 3;
         public static final int BACK_LEFT_ROTATION_CANCODER_ID      = 6;
         public static final int BACK_RIGHT_ROTATION_CANCODER_ID     = 1;
+
+
+        //WMP
+        public static final int INTAKE_LIMIT_SWITCH_CHANNEL         = 0; //change this cero
```
Comment (ebay-kid) [inline src/main/java/frc/robot/Constants.java]: `SWITCH_PORT` is the naming convention we normally use

**Review by ebay-kid — COMMENTED** [review]
small changes in naming stuff but your code itself is perfectly fine

if you want to change it before merge feel free to do so, otherwise it'll get merged in maybe a week when the intake is actually built
